# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hamming(object):
    def setupUi(self, Hamming):
        Hamming.setObjectName("Hamming")
        Hamming.resize(720, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Hamming.sizePolicy().hasHeightForWidth())
        Hamming.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(Hamming)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 721, 831))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radioPar = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioPar.setObjectName("radioPar")
        self.horizontalLayout.addWidget(self.radioPar)
        self.radioImpar = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioImpar.setObjectName("radioImpar")
        self.horizontalLayout.addWidget(self.radioImpar)
        self.convertBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.convertBtn.setObjectName("convertBtn")
        self.horizontalLayout.addWidget(self.convertBtn)
        self.checkBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.checkBtn.setObjectName("checkBtn")
        self.horizontalLayout.addWidget(self.checkBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.hexaLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hexaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hexaLabel.setObjectName("hexaLabel")
        self.horizontalLayout_3.addWidget(self.hexaLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.decimalLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.decimalLabel.setText("")
        self.decimalLabel.setTextFormat(QtCore.Qt.AutoText)
        self.decimalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.decimalLabel.setObjectName("decimalLabel")
        self.horizontalLayout_4.addWidget(self.decimalLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.bcdLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bcdLabel.setText("")
        self.bcdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bcdLabel.setObjectName("bcdLabel")
        self.horizontalLayout_5.addWidget(self.bcdLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.hammingTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hammingTable.sizePolicy().hasHeightForWidth())
        self.hammingTable.setSizePolicy(sizePolicy)
        self.hammingTable.setMinimumSize(QtCore.QSize(550, 200))
        self.hammingTable.setMaximumSize(QtCore.QSize(540, 180))
        self.hammingTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hammingTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hammingTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.hammingTable.setAutoScroll(False)
        self.hammingTable.setAlternatingRowColors(False)
        self.hammingTable.setRowCount(7)
        self.hammingTable.setColumnCount(17)
        self.hammingTable.setObjectName("hammingTable")
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.hammingTable.setItem(3, 4, item)
        self.hammingTable.horizontalHeader().setCascadingSectionResizes(True)
        self.hammingTable.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.hammingTable, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hammingResult = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hammingResult.setText("")
        self.hammingResult.setObjectName("hammingResult")
        self.horizontalLayout_2.addWidget(self.hammingResult)
        self.copyBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.copyBtn.setObjectName("copyBtn")
        self.horizontalLayout_2.addWidget(self.copyBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.repairTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repairTable.sizePolicy().hasHeightForWidth())
        self.repairTable.setSizePolicy(sizePolicy)
        self.repairTable.setMinimumSize(QtCore.QSize(620, 180))
        self.repairTable.setMaximumSize(QtCore.QSize(620, 180))
        self.repairTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repairTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repairTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.repairTable.setAutoScroll(False)
        self.repairTable.setAlternatingRowColors(False)
        self.repairTable.setRowCount(6)
        self.repairTable.setColumnCount(18)
        self.repairTable.setObjectName("repairTable")
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.repairTable.setItem(3, 4, item)
        self.repairTable.horizontalHeader().setCascadingSectionResizes(True)
        self.repairTable.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.repairTable, 0, QtCore.Qt.AlignHCenter)
        self.errorLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        Hamming.setCentralWidget(self.centralWidget)

        self.retranslateUi(Hamming)
        QtCore.QMetaObject.connectSlotsByName(Hamming)

    def retranslateUi(self, Hamming):
        _translate = QtCore.QCoreApplication.translate
        Hamming.setWindowTitle(_translate("Hamming", "Hamming"))
        self.label.setText(_translate("Hamming", "Paridad:"))
        self.radioPar.setText(_translate("Hamming", "Par"))
        self.radioImpar.setText(_translate("Hamming", "Impar"))
        self.convertBtn.setText(_translate("Hamming", "Convertir"))
        self.checkBtn.setText(_translate("Hamming", "Reparar"))
        self.label_3.setText(_translate("Hamming", "Hexadecimal:"))
        self.hexaLabel.setText(_translate("Hamming", " "))
        self.label_4.setText(_translate("Hamming", "Decimal:"))
        self.label_5.setText(_translate("Hamming", "BCD:"))
        item = self.hammingTable.verticalHeaderItem(0)
        item.setText(_translate("Hamming", "Datos (sin paridad)"))
        item = self.hammingTable.verticalHeaderItem(1)
        item.setText(_translate("Hamming", "p1"))
        item = self.hammingTable.verticalHeaderItem(2)
        item.setText(_translate("Hamming", "p2"))
        item = self.hammingTable.verticalHeaderItem(3)
        item.setText(_translate("Hamming", "p4"))
        item = self.hammingTable.verticalHeaderItem(4)
        item.setText(_translate("Hamming", "p8"))
        item = self.hammingTable.verticalHeaderItem(5)
        item.setText(_translate("Hamming", "p16"))
        item = self.hammingTable.verticalHeaderItem(6)
        item.setText(_translate("Hamming", "Datos (con paridad)"))
        item = self.hammingTable.horizontalHeaderItem(0)
        item.setText(_translate("Hamming", "p1"))
        item = self.hammingTable.horizontalHeaderItem(1)
        item.setText(_translate("Hamming", "p2"))
        item = self.hammingTable.horizontalHeaderItem(2)
        item.setText(_translate("Hamming", "d1"))
        item = self.hammingTable.horizontalHeaderItem(3)
        item.setText(_translate("Hamming", "p4"))
        item = self.hammingTable.horizontalHeaderItem(4)
        item.setText(_translate("Hamming", "d2"))
        item = self.hammingTable.horizontalHeaderItem(5)
        item.setText(_translate("Hamming", "d3"))
        item = self.hammingTable.horizontalHeaderItem(6)
        item.setText(_translate("Hamming", "d4"))
        item = self.hammingTable.horizontalHeaderItem(7)
        item.setText(_translate("Hamming", "p8"))
        item = self.hammingTable.horizontalHeaderItem(8)
        item.setText(_translate("Hamming", "d5"))
        item = self.hammingTable.horizontalHeaderItem(9)
        item.setText(_translate("Hamming", "d6"))
        item = self.hammingTable.horizontalHeaderItem(10)
        item.setText(_translate("Hamming", "d7"))
        item = self.hammingTable.horizontalHeaderItem(11)
        item.setText(_translate("Hamming", "d8"))
        item = self.hammingTable.horizontalHeaderItem(12)
        item.setText(_translate("Hamming", "d9"))
        item = self.hammingTable.horizontalHeaderItem(13)
        item.setText(_translate("Hamming", "d10"))
        item = self.hammingTable.horizontalHeaderItem(14)
        item.setText(_translate("Hamming", "d11"))
        item = self.hammingTable.horizontalHeaderItem(15)
        item.setText(_translate("Hamming", "p16"))
        item = self.hammingTable.horizontalHeaderItem(16)
        item.setText(_translate("Hamming", "d12"))
        __sortingEnabled = self.hammingTable.isSortingEnabled()
        self.hammingTable.setSortingEnabled(False)
        self.hammingTable.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Hamming", "Resultado Hamming:"))
        self.copyBtn.setText(_translate("Hamming", "Usar como entrada"))
        item = self.repairTable.verticalHeaderItem(0)
        item.setText(_translate("Hamming", "Datos recibidos"))
        item = self.repairTable.verticalHeaderItem(1)
        item.setText(_translate("Hamming", "p1"))
        item = self.repairTable.verticalHeaderItem(2)
        item.setText(_translate("Hamming", "p2"))
        item = self.repairTable.verticalHeaderItem(3)
        item.setText(_translate("Hamming", "p4"))
        item = self.repairTable.verticalHeaderItem(4)
        item.setText(_translate("Hamming", "p8"))
        item = self.repairTable.verticalHeaderItem(5)
        item.setText(_translate("Hamming", "p16"))
        item = self.repairTable.horizontalHeaderItem(0)
        item.setText(_translate("Hamming", "p1"))
        item = self.repairTable.horizontalHeaderItem(1)
        item.setText(_translate("Hamming", "p2"))
        item = self.repairTable.horizontalHeaderItem(2)
        item.setText(_translate("Hamming", "d1"))
        item = self.repairTable.horizontalHeaderItem(3)
        item.setText(_translate("Hamming", "p4"))
        item = self.repairTable.horizontalHeaderItem(4)
        item.setText(_translate("Hamming", "d2"))
        item = self.repairTable.horizontalHeaderItem(5)
        item.setText(_translate("Hamming", "d3"))
        item = self.repairTable.horizontalHeaderItem(6)
        item.setText(_translate("Hamming", "d4"))
        item = self.repairTable.horizontalHeaderItem(7)
        item.setText(_translate("Hamming", "p8"))
        item = self.repairTable.horizontalHeaderItem(8)
        item.setText(_translate("Hamming", "d5"))
        item = self.repairTable.horizontalHeaderItem(9)
        item.setText(_translate("Hamming", "d6"))
        item = self.repairTable.horizontalHeaderItem(10)
        item.setText(_translate("Hamming", "d7"))
        item = self.repairTable.horizontalHeaderItem(11)
        item.setText(_translate("Hamming", "d8"))
        item = self.repairTable.horizontalHeaderItem(12)
        item.setText(_translate("Hamming", "d9"))
        item = self.repairTable.horizontalHeaderItem(13)
        item.setText(_translate("Hamming", "d10"))
        item = self.repairTable.horizontalHeaderItem(14)
        item.setText(_translate("Hamming", "d11"))
        item = self.repairTable.horizontalHeaderItem(15)
        item.setText(_translate("Hamming", "p16"))
        item = self.repairTable.horizontalHeaderItem(16)
        item.setText(_translate("Hamming", "d12"))
        item = self.repairTable.horizontalHeaderItem(17)
        item.setText(_translate("Hamming", "Prueba de paridad"))
        __sortingEnabled = self.repairTable.isSortingEnabled()
        self.repairTable.setSortingEnabled(False)
        self.repairTable.setSortingEnabled(__sortingEnabled)


